import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Home,Users,Wrench,Building2,LayoutDashboard,FileText,Plus,Trash2,Edit,LogOut,Download,X,Mail,Lock,Eye,EyeOff,Loader2,ShieldCheck,Filter,RotateCcw,ClipboardList,Wallet,TrendingUp,Coins,Check}from'lucide-react';import{BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid,LabelList}from'recharts';import'./style.css';
const API=import.meta.env.VITE_API_URL||(location.hostname==='localhost'?'http://localhost:4000/api':'/api');

let toastListeners=[];
function showToast(msg,type='success'){toastListeners.forEach(l=>l(msg,type))}
function useToastFeed(){const[toasts,setToasts]=useState([]);useEffect(()=>{const l=(msg,type)=>{const id=Date.now()+Math.random();setToasts(t=>[...t,{id,msg,type}]);setTimeout(()=>setToasts(t=>t.filter(x=>x.id!==id)),3500)};toastListeners.push(l);return()=>{toastListeners=toastListeners.filter(x=>x!==l)}},[]);return toasts}
function Toaster(){const toasts=useToastFeed();return <div className="toasts">{toasts.map(t=><div key={t.id} className={'toast '+t.type}>{t.msg}</div>)}</div>}

function useApi(){const token=localStorage.token;return async(path,opts={})=>{const r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token,...opts.headers}});if(r.status===401){localStorage.clear();location.reload();return new Promise(()=>{})}const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||'حدث خطأ غير متوقع');return j.data}}

async function runAction(fn,successMsg){try{await fn();if(successMsg)showToast(successMsg,'success')}catch(e){showToast(e.message||'فشلت العملية','error')}}

const IS_DEV=location.hostname==='localhost';
const LOGIN_FEATURES=[[Building2,'إدارة الفلل والشقق بشكل مركزي'],[Wrench,'تتبع كشوف الصيانة والفنيين'],[LayoutDashboard,'لوحة تحكم ومؤشرات أداء لحظية']];
function Login({onOk}){const[form,setForm]=useState(IS_DEV?{email:'admin@maintenance.local',password:'Admin@12345'}:{email:'',password:''});const[err,setErr]=useState('');const[busy,setBusy]=useState(false);const[showPwd,setShowPwd]=useState(false);async function login(e){e.preventDefault();setErr('');setBusy(true);try{const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(!r.ok)throw new Error(j.message);localStorage.token=j.data.token;localStorage.user=JSON.stringify(j.data.user);onOk(j.data.user)}catch(e){setErr('بيانات الدخول غير صحيحة')}finally{setBusy(false)}}
return <div className="login">
  <div className="loginShell">
    <div className="loginBrandPanel">
      <div className="loginBrandTop"><div className="logo logoLight"><Building2 size={22}/>Maintenance<span>Pro</span></div></div>
      <div className="loginBrandMid">
        <h1>نظام متكامل لإدارة<br/>أعمال الصيانة اليومية</h1>
        <p>تابع كشوف الصيانة، الفنيين، والفلل والشقق من مكان واحد، بأداء سريع وواجهة عربية كاملة.</p>
        <ul className="loginFeatures">{LOGIN_FEATURES.map(([Icon,label],i)=><li key={i}><span className="loginFeatureIcon"><Icon size={16}/></span>{label}</li>)}</ul>
      </div>
      <div className="loginBrandBottom"><ShieldCheck size={15}/> بياناتك محمية ومشفّرة</div>
    </div>
    <div className="loginFormPanel">
      <form onSubmit={login} className="loginCard">
        <h2>تسجيل الدخول</h2>
        <small className="loginSub">أدخل بياناتك للوصول إلى لوحة التحكم</small>
        <Field label="البريد الإلكتروني" required>
          <div className="inputIcon"><Mail size={16}/><input required type="email" placeholder="name@company.com" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div>
        </Field>
        <Field label="كلمة المرور" required>
          <div className="inputIcon"><Lock size={16}/><input required type={showPwd?'text':'password'} placeholder="••••••••" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button type="button" className="pwdToggle" onClick={()=>setShowPwd(s=>!s)} aria-label="إظهار كلمة المرور">{showPwd?<EyeOff size={16}/>:<Eye size={16}/>}</button></div>
        </Field>
        {err&&<p className="err">{err}</p>}
        <button disabled={busy}>{busy?<><Loader2 size={16} className="spin"/>جارٍ الدخول...</>:'دخول النظام'}</button>
        {IS_DEV&&<div className="demoHint">Demo: admin@maintenance.local / Admin@12345</div>}
      </form>
    </div>
  </div>
</div>}

function App(){const[user,setUser]=useState(()=>localStorage.user?JSON.parse(localStorage.user):null);const[page,setPage]=useState('dashboard');if(!user)return <><Login onOk={setUser}/><Toaster/></>;const logout=()=>{localStorage.clear();setUser(null)};const items=[['dashboard','لوحة التحكم',LayoutDashboard],['records','كشف الصيانة',FileText],['villas','الفلل',Building2],['apartments','الشقق',Home],['technicians','الفنيين',Wrench],['users','المستخدمين',Users]];return <div className="app" dir="rtl"><aside><div className="logo">Maintenance<span>Pro</span></div>{items.map(([id,t,I])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><I size={18}/>{t}</button>)}<button onClick={logout}><LogOut size={18}/>خروج</button></aside><main><header><div><h2>{items.find(i=>i[0]===page)?.[1]}</h2><p>نظام إدارة كشف الصيانة اليومي للفلل والشقق</p></div><div className="user"><div className="userAvatar">{user.name?.[0]}</div><div className="userMeta"><span className="userName">{user.name}</span><span className={'roleBadge role-'+user.role}>{ROLE_LABELS[user.role]||user.role}</span></div></div></header>{page==='dashboard'&&<Dashboard/>}{page==='records'&&<Records/>}{page==='villas'&&<Villas user={user}/>}{page==='apartments'&&<Apartments user={user}/>}{page==='technicians'&&<Technicians user={user}/>}{page==='users'&&<UsersPage user={user}/>}</main><Toaster/></div>}

function monthStart(){const t=new Date();return new Date(t.getFullYear(),t.getMonth(),1).toISOString().slice(0,10)}
function todayStr(){return new Date().toISOString().slice(0,10)}
const DEFAULT_DASH_FILTERS={from:monthStart(),to:todayStr(),villa_id:'',technician_id:''};
function Dashboard(){const api=useApi();const[d,setD]=useState(null);const[villas,setVillas]=useState([]);const[techs,setTechs]=useState([]);const[f,setF]=useState(DEFAULT_DASH_FILTERS);
useEffect(()=>{api('/villas').then(setVillas);api('/technicians').then(setTechs)},[]);
useEffect(()=>{const qs=new URLSearchParams(Object.fromEntries(Object.entries(f).filter(([,v])=>v))).toString();api('/dashboard'+(qs?'?'+qs:'')).then(setD)},[f]);
const isFiltered=f.villa_id||f.technician_id||f.from!==DEFAULT_DASH_FILTERS.from||f.to!==DEFAULT_DASH_FILTERS.to;
if(!d)return <Loader/>;
return <>
<Panel title={<span className="panelTitleIcon"><Filter size={16}/>تصفية النتائج</span>}>
  <div className="filterBar">
    <Field label="من تاريخ"><input type="date" value={f.from} onChange={e=>setF({...f,from:e.target.value})}/></Field>
    <Field label="إلى تاريخ"><input type="date" value={f.to} onChange={e=>setF({...f,to:e.target.value})}/></Field>
    <Field label="الفيلا"><select value={f.villa_id} onChange={e=>setF({...f,villa_id:e.target.value})}><option value="">كل الفلل</option>{villas.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></Field>
    <Field label="الفني"><select value={f.technician_id} onChange={e=>setF({...f,technician_id:e.target.value})}><option value="">كل الفنيين</option>{techs.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field>
    <button type="button" className="secondary filterReset" onClick={()=>setF(DEFAULT_DASH_FILTERS)}><RotateCcw size={14}/>إعادة تعيين</button>
  </div>
</Panel>
<section className="cards">
  <Card t="أعمال اليوم" v={d.today.records} icon={ClipboardList} tone="teal"/>
  <Card t="تكلفة اليوم" v={Number(d.today.cost).toFixed(2)+' AED'} icon={Wallet} tone="amber"/>
  <Card t={isFiltered?'أعمال الفترة المحددة':'أعمال الشهر'} v={isFiltered?d.filtered.records:d.month.records} icon={TrendingUp} tone="blue"/>
  <Card t={isFiltered?'تكلفة الفترة المحددة':'تكلفة الشهر'} v={Number(isFiltered?d.filtered.cost:d.month.cost).toFixed(2)+' AED'} icon={Coins} tone="purple"/>
</section>
<section className="grid2">
<Panel title="الأعمال حسب الفني">{d.byTech.every(x=>x.total===0)?<EmptyChart/>:<div dir="ltr"><ResponsiveContainer height={280}><BarChart data={d.byTech} margin={{top:8,right:8,left:0,bottom:50}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:11}} interval={0} angle={-35} textAnchor="end" height={60}/><YAxis allowDecimals={false} width={28} tick={{fontSize:12}}/><Tooltip formatter={v=>[v+' عمل','الإجمالي']}/><Bar dataKey="total" fill="#0f766e" radius={[6,6,0,0]} maxBarSize={48} isAnimationActive={false}><LabelList dataKey="total" position="top" style={{fontSize:12,fontWeight:700,fill:'#0f766e'}}/></Bar></BarChart></ResponsiveContainer></div>}</Panel>
<Panel title="الأعمال حسب الفيلا">{d.byVilla.every(x=>x.total===0)?<EmptyChart/>:<div dir="ltr"><ResponsiveContainer height={280}><BarChart data={d.byVilla} margin={{top:8,right:8,left:0,bottom:50}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:11}} interval={0} angle={-35} textAnchor="end" height={60}/><YAxis allowDecimals={false} width={28} tick={{fontSize:12}}/><Tooltip formatter={v=>[v+' عمل','الإجمالي']}/><Bar dataKey="total" fill="#0e7490" radius={[6,6,0,0]} maxBarSize={48} isAnimationActive={false}><LabelList dataKey="total" position="top" style={{fontSize:12,fontWeight:700,fill:'#0e7490'}}/></Bar></BarChart></ResponsiveContainer></div>}</Panel>
</section><Panel title="آخر السجلات"><Table rows={d.recent} cols={['record_date','villa_name','spare_part_cost']}/></Panel></>}

function Card({t,v,icon:Icon,tone='teal'}){return <div className="card"><div className={'cardIcon tone-'+tone}>{Icon&&<Icon size={18}/>}</div><div className="cardBody"><p>{t}</p><h3>{v}</h3></div></div>}
function EmptyChart(){return <div className="emptyChart">لا توجد بيانات كافية لعرض الرسم البياني لهذه الفترة</div>}
function Panel(p){return <section className="panel"><h3>{p.title}</h3>{p.children}</section>}
function Loader(){return <div className="panel">جاري التحميل...</div>}
function Field({label,required,wide,children}){return <label className={'field'+(wide?' wide':'')}><span>{label}{required&&<b className="req">*</b>}</span>{children}</label>}
function Modal({open,onClose,title,children}){useEffect(()=>{if(!open)return;const onKey=e=>{if(e.key==='Escape')onClose()};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey)},[open,onClose]);if(!open)return null;return <div className="modalOverlay" onClick={onClose}><div className="modalBox" onClick={e=>e.stopPropagation()}><div className="modalHead"><h3>{title}</h3><button type="button" className="iconBtn" onClick={onClose}><X size={18}/></button></div>{children}</div></div>}

function Records(){const api=useApi();const[rows,setRows]=useState([]),[villas,setVillas]=useState([]),[apts,setApts]=useState([]),[techs,setTechs]=useState([]);const empty={record_date:new Date().toISOString().slice(0,10),villa_id:'',apartment_id:'',description:'',technician_ids:[],reported_time:'',completed_time:'',spare_part:'',spare_part_cost:0,notes:''};const[form,setForm]=useState(empty);const[editing,setEditing]=useState(null);const[modalOpen,setModalOpen]=useState(false);const load=()=>{api('/records').then(setRows);api('/villas').then(setVillas);api('/apartments').then(setApts);api('/technicians').then(setTechs)};useEffect(()=>{load()},[]);function openAdd(){setEditing(null);setForm(empty);setModalOpen(true)}function closeModal(){setModalOpen(false)}async function save(e){e.preventDefault();if(form.technician_ids.length===0)return showToast('اختر فنيًا واحدًا على الأقل','error');await runAction(async()=>{await api(editing?'/records/'+editing:'/records',{method:editing?'PUT':'POST',body:JSON.stringify(form)});setForm(empty);setEditing(null);setModalOpen(false);load()},editing?'تم حفظ التعديل':'تمت إضافة السجل')}function edit(r){setEditing(r.id);setForm({...r,record_date:String(r.record_date).slice(0,10),reported_time:r.reported_time||'',completed_time:r.completed_time||'',technician_ids:r.technician_ids?String(r.technician_ids).split(',').map(Number):[]});setModalOpen(true)}async function remove(r){if(!confirm('تأكيد حذف سجل الصيانة هذا؟ لا يمكن التراجع.'))return;await runAction(async()=>{await api('/records/'+r.id,{method:'DELETE'});load()},'تم حذف السجل')}function csv(){let c='Date,Villa,Apartment,Description,Technician,Reported,Completed,Part,Cost\n'+rows.map(r=>[r.record_date,r.villa_name,r.apartment_no,r.description,r.technician_name,r.reported_time,r.completed_time,r.spare_part,r.spare_part_cost].map(x=>'"'+(x??'')+'"').join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([c]));a.download='maintenance-records.csv';a.click()}return <><Panel title="كشف الصيانة"><div className="panelActions"><button onClick={openAdd}><Plus size={16}/>إضافة سجل صيانة</button><button className="secondary" onClick={csv}><Download size={16}/>تصدير CSV / Excel</button></div><Table rows={rows.map(r=>({...r,status:r.completed_time?'مكتمل':'قيد التنفيذ'}))} cols={['record_date','villa_name','apartment_no','description','technician_name','status','spare_part_cost']} searchable actions={r=><><button onClick={()=>edit(r)}><Edit size={15}/></button><button className="danger" onClick={()=>remove(r)}><Trash2 size={15}/></button></>}/></Panel><Modal open={modalOpen} onClose={closeModal} title={editing?'تعديل سجل صيانة':'إضافة سجل صيانة'}><form className="form" onSubmit={save}>
<div className="formSection wide"><span className="formSectionTitle">بيانات الموقع</span></div>
<Field label="التاريخ" required><input required type="date" value={form.record_date} onChange={e=>setForm({...form,record_date:e.target.value})}/></Field>
<Field label="الفيلا" required><select required value={form.villa_id} onChange={e=>setForm({...form,villa_id:e.target.value,apartment_id:''})}><option value="">اختر الفيلا</option>{villas.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></Field>
<Field label="الشقة" required><select required disabled={!form.villa_id} value={form.apartment_id} onChange={e=>setForm({...form,apartment_id:e.target.value})}><option value="">{form.villa_id?'اختر الشقة':'اختر الفيلا أولاً'}</option>{apts.filter(a=>a.villa_id==form.villa_id).map(a=><option key={a.id} value={a.id}>{a.apartment_no}</option>)}</select></Field>
<Field label="الفني (يمكن اختيار أكثر من فني)" required wide><div className="chipPicker">{techs.map(t=>{const sel=form.technician_ids.includes(t.id);return <button type="button" key={t.id} className={'chip'+(sel?' chipSelected':'')} onClick={()=>setForm({...form,technician_ids:sel?form.technician_ids.filter(id=>id!==t.id):[...form.technician_ids,t.id]})}>{sel&&<Check size={13}/>}{t.name}</button>})}</div>{form.technician_ids.length===0&&<small className="chipHint">اختر فنيًا واحدًا على الأقل</small>}</Field>
<div className="formSection wide"><span className="formSectionTitle">تنفيذ العمل</span></div>
<Field label="وقت الورود"><input type="time" value={form.reported_time} onChange={e=>setForm({...form,reported_time:e.target.value})}/></Field>
<Field label="وقت الانتهاء"><input type="time" value={form.completed_time} onChange={e=>setForm({...form,completed_time:e.target.value})}/></Field>
<Field label="قطعة الغيار"><input value={form.spare_part||''} onChange={e=>setForm({...form,spare_part:e.target.value})}/></Field>
<Field label="التكلفة (AED)"><input type="number" value={form.spare_part_cost} onChange={e=>setForm({...form,spare_part_cost:e.target.value})}/></Field>
<div className="formSection wide"><span className="formSectionTitle">التفاصيل</span></div>
<Field label="الوصف" required wide><textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field>
<Field label="ملاحظات" wide><textarea value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></Field>
<button><Plus size={16}/>{editing?'حفظ التعديل':'إضافة السجل'}</button><button type="button" className="secondary" onClick={closeModal}>إلغاء</button></form></Modal></>}

function Villas({user}){const api=useApi();const isAdmin=user?.role==='ADMIN';const[villas,setVillas]=useState([]);const[apts,setApts]=useState([]);const emptyVilla={name:'',area:'',notes:'',is_active:1};const[villa,setVilla]=useState(emptyVilla);const[editingVilla,setEditingVilla]=useState(null);const[modalOpen,setModalOpen]=useState(false);const load=()=>{api('/villas').then(setVillas);api('/apartments').then(setApts)};useEffect(()=>{load()},[]);function openAdd(){setEditingVilla(null);setVilla(emptyVilla);setModalOpen(true)}function closeModal(){setModalOpen(false)}async function saveVilla(e){e.preventDefault();await runAction(async()=>{await api(editingVilla?'/villas/'+editingVilla:'/villas',{method:editingVilla?'PUT':'POST',body:JSON.stringify(villa)});setVilla(emptyVilla);setEditingVilla(null);setModalOpen(false);load()},editingVilla?'تم تعديل الفيلا':'تمت إضافة الفيلا')}async function removeVilla(r){if(!confirm(`تأكيد حذف فيلا "${r.name}"؟ سيتم حذف كل الشقق المرتبطة بها.`))return;await runAction(async()=>{await api('/villas/'+r.id,{method:'DELETE'});load()},'تم حذف الفيلا')}const rows=villas.map(v=>({...v,apartments_count:apts.filter(a=>a.villa_id===v.id).length}));return <><Panel title="الفلل"><div className="panelActions"><button onClick={openAdd}><Plus size={16}/>إضافة فيلا</button></div><Table rows={rows} cols={['name','area','apartments_count','is_active']} searchable actions={isAdmin?r=><><button onClick={()=>{setEditingVilla(r.id);setVilla({name:r.name,area:r.area||'',notes:r.notes||'',is_active:r.is_active});setModalOpen(true)}}><Edit size={15}/></button><button className="danger" onClick={()=>removeVilla(r)}><Trash2 size={15}/></button></>:null}/></Panel><Modal open={modalOpen} onClose={closeModal} title={editingVilla?'تعديل فيلا':'إضافة فيلا'}><form className="form compact" onSubmit={saveVilla}><Field label="اسم الفيلا" required><input required placeholder="مثال: فيلا الياسمين" value={villa.name} onChange={e=>setVilla({...villa,name:e.target.value})}/></Field><Field label="المنطقة"><input placeholder="مثال: دبي" value={villa.area} onChange={e=>setVilla({...villa,area:e.target.value})}/></Field><Field label="ملاحظات"><input value={villa.notes||''} onChange={e=>setVilla({...villa,notes:e.target.value})}/></Field>{editingVilla&&<Field label="الحالة"><select value={villa.is_active} onChange={e=>setVilla({...villa,is_active:Number(e.target.value)})}><option value={1}>فعّال</option><option value={0}>متوقف</option></select></Field>}<button>{editingVilla?'حفظ التعديل':'إضافة'}</button><button type="button" className="secondary" onClick={closeModal}>إلغاء</button></form></Modal></>}

function Apartments({user}){const api=useApi();const isAdmin=user?.role==='ADMIN';const[villas,setVillas]=useState([]),[apts,setApts]=useState([]);const emptyApt={villa_id:'',apartment_no:'',floor:''};const[apt,setApt]=useState(emptyApt);const[editingApt,setEditingApt]=useState(null);const[modalOpen,setModalOpen]=useState(false);const load=()=>{api('/villas').then(setVillas);api('/apartments').then(setApts)};useEffect(()=>{load()},[]);function openAdd(){setEditingApt(null);setApt(emptyApt);setModalOpen(true)}function closeModal(){setModalOpen(false)}async function saveApt(e){e.preventDefault();await runAction(async()=>{await api(editingApt?'/apartments/'+editingApt:'/apartments',{method:editingApt?'PUT':'POST',body:JSON.stringify(apt)});setApt(emptyApt);setEditingApt(null);setModalOpen(false);load()},editingApt?'تم تعديل الشقة':'تمت إضافة الشقة')}async function removeApt(r){if(!confirm(`تأكيد حذف الشقة "${r.apartment_no}"؟`))return;await runAction(async()=>{await api('/apartments/'+r.id,{method:'DELETE'});load()},'تم حذف الشقة')}return <><Panel title="الشقق"><div className="panelActions"><button onClick={openAdd}><Plus size={16}/>إضافة شقة</button></div><Table rows={apts} cols={['villa_name','apartment_no','floor']} searchable actions={isAdmin?r=><><button onClick={()=>{setEditingApt(r.id);setApt({villa_id:r.villa_id,apartment_no:r.apartment_no,floor:r.floor||''});setModalOpen(true)}}><Edit size={15}/></button><button className="danger" onClick={()=>removeApt(r)}><Trash2 size={15}/></button></>:null}/></Panel><Modal open={modalOpen} onClose={closeModal} title={editingApt?'تعديل شقة':'إضافة شقة داخل فيلا'}><form className="form compact" onSubmit={saveApt}><Field label="الفيلا" required><select required value={apt.villa_id} onChange={e=>setApt({...apt,villa_id:e.target.value})}><option value="">اختر الفيلا</option>{villas.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></Field><Field label="رقم الشقة" required><input required value={apt.apartment_no} onChange={e=>setApt({...apt,apartment_no:e.target.value})}/></Field><Field label="الدور"><input value={apt.floor||''} onChange={e=>setApt({...apt,floor:e.target.value})}/></Field><button>{editingApt?'حفظ التعديل':'إضافة'}</button><button type="button" className="secondary" onClick={closeModal}>إلغاء</button></form></Modal></>}

const emptyTech={name:'',specialty:'',phone:'',notes:''};
function Technicians({user}){const api=useApi();const isAdmin=user?.role==='ADMIN';const[rows,setRows]=useState([]);const[items,setItems]=useState([{...emptyTech}]);const[editing,setEditing]=useState(null);const[modalOpen,setModalOpen]=useState(false);const load=()=>api('/technicians').then(setRows);useEffect(()=>{load()},[]);
function openAdd(){setEditing(null);setItems([{...emptyTech}]);setModalOpen(true)}
function closeModal(){setModalOpen(false)}
function updateItem(i,f,v){setItems(items.map((it,idx)=>idx===i?{...it,[f]:v}:it))}
function addRow(){setItems([...items,{...emptyTech}])}
function removeRow(i){setItems(items.filter((_,idx)=>idx!==i))}
async function save(e){e.preventDefault();await runAction(async()=>{if(editing){await api('/technicians/'+editing,{method:'PUT',body:JSON.stringify(items[0])})}else{for(const it of items){await api('/technicians',{method:'POST',body:JSON.stringify(it)})}}setItems([{...emptyTech}]);setEditing(null);setModalOpen(false);load()},editing?'تم حفظ التعديل':items.length>1?`تمت إضافة ${items.length} فنيين`:'تمت إضافة الفني')}
function startEdit(r){setEditing(r.id);setItems([{name:r.name,specialty:r.specialty||'',phone:r.phone||'',notes:r.notes||''}]);setModalOpen(true)}
async function remove(r){if(!confirm('تأكيد الحذف؟'))return;await runAction(async()=>{await api('/technicians/'+r.id,{method:'DELETE'});load()},'تم الحذف')}
return <><Panel title="الفنيين"><div className="panelActions"><button onClick={openAdd}><Plus size={16}/>إضافة فني</button></div><Table rows={rows} cols={['name','specialty','phone','notes']} searchable actions={isAdmin?r=><><button onClick={()=>startEdit(r)}><Edit size={15}/></button><button className="danger" onClick={()=>remove(r)}><Trash2 size={15}/></button></>:null}/></Panel>
<Modal open={modalOpen} onClose={closeModal} title={editing?'تعديل فني':'إضافة فنيين'}><form className="form compact" onSubmit={save}>
{items.map((it,i)=><div key={i} className="techRow">
{!editing&&items.length>1&&<div className="techRowHead"><span>فني {i+1}</span><button type="button" className="iconBtn" onClick={()=>removeRow(i)}><X size={14}/></button></div>}
<Field label="الاسم" required><input required value={it.name} onChange={e=>updateItem(i,'name',e.target.value)}/></Field>
<Field label="التخصص"><input value={it.specialty} onChange={e=>updateItem(i,'specialty',e.target.value)}/></Field>
<Field label="الهاتف"><input value={it.phone} onChange={e=>updateItem(i,'phone',e.target.value)}/></Field>
<Field label="ملاحظات"><input value={it.notes} onChange={e=>updateItem(i,'notes',e.target.value)}/></Field>
</div>)}
{!editing&&<button type="button" className="secondary" onClick={addRow}><Plus size={14}/>إضافة فني آخر</button>}
<button>{editing?'حفظ التعديل':items.length>1?`إضافة ${items.length} فنيين`:'إضافة'}</button><button type="button" className="secondary" onClick={closeModal}>إلغاء</button>
</form></Modal></>}
function UsersPage({user}){return <Simple title="المستخدمين" path="/users" fields={['name','email','password','role']} labels={['الاسم','الإيميل','كلمة المرور','الدور']} required={['name','email']} selectOptions={{role:[['SUPERVISOR','مشرف (SUPERVISOR)'],['ADMIN','أدمن (ADMIN)']]}} user={user} currentUserId={user?.id}/>}
function Simple({title,path,fields,labels,required=[],selectOptions={},user,currentUserId}){const api=useApi();const isAdmin=user?.role==='ADMIN';const[rows,setRows]=useState([]);const init=Object.fromEntries(fields.map(f=>[f,selectOptions[f]?selectOptions[f][0][0]:'']));const[form,setForm]=useState(init);const[editing,setEditing]=useState(null);const[modalOpen,setModalOpen]=useState(false);const load=()=>api(path).then(setRows);useEffect(()=>{load()},[path]);function openAdd(){setEditing(null);setForm(init);setModalOpen(true)}function closeModal(){setModalOpen(false)}async function save(e){e.preventDefault();await runAction(async()=>{await api(editing?path+'/'+editing:path,{method:editing?'PUT':'POST',body:JSON.stringify(form)});setForm(init);setEditing(null);setModalOpen(false);load()},editing?'تم حفظ التعديل':'تمت الإضافة')}function startEdit(r){setEditing(r.id);setForm({...init,...r,password:''});setModalOpen(true)}async function remove(r){if(!confirm(`تأكيد الحذف؟`))return;await runAction(async()=>{await api(path+'/'+r.id,{method:'DELETE'});load()},'تم الحذف')}return <><Panel title={title}><div className="panelActions"><button onClick={openAdd}><Plus size={16}/>إضافة</button></div><Table rows={rows} cols={fields.filter(f=>f!=='password')} searchable actions={isAdmin?r=><>{r.id!==currentUserId&&<><button onClick={()=>startEdit(r)}><Edit size={15}/></button><button className="danger" onClick={()=>remove(r)}><Trash2 size={15}/></button></>}</>:null}/></Panel><Modal open={modalOpen} onClose={closeModal} title={editing?'تعديل':title}><form className="form compact" onSubmit={save}>{fields.map((f,i)=><Field key={f} label={labels[i]+(editing&&f==='password'?' (اتركها فارغة لعدم التغيير)':'')} required={required.includes(f)}>{selectOptions[f]?<select value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})}>{selectOptions[f].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:<input required={required.includes(f)} type={f==='password'?'password':'text'} value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})}/>}</Field>)}<button>{editing?'حفظ التعديل':'إضافة'}</button><button type="button" className="secondary" onClick={closeModal}>إلغاء</button></form></Modal></>}

const FIELD_LABELS={record_date:'التاريخ',villa_name:'الفيلا',apartment_no:'رقم الشقة',description:'الوصف',technician_name:'الفني',reported_time:'وقت الورود',completed_time:'وقت الانتهاء',spare_part:'قطعة الغيار',spare_part_cost:'التكلفة',name:'الاسم',area:'المنطقة',notes:'ملاحظات',floor:'الدور',specialty:'التخصص',phone:'الهاتف',email:'الإيميل',role:'الدور',created_by_name:'أضيف بواسطة',status:'الحالة',apartments_count:'عدد الشقق',is_active:'الحالة'};
const ROLE_LABELS={ADMIN:'أدمن',SUPERVISOR:'مشرف'};
function formatCell(c,v){if(c==='status')return <span className={'statusBadge '+(v==='مكتمل'?'status-on':'status-pending')}>{v}</span>;if(v===null||v===undefined||v==='')return'-';if(c==='record_date')return new Date(v).toLocaleDateString('ar-AE');if(c.endsWith('_time'))return String(v).slice(0,5);if(c==='spare_part_cost')return Number(v).toFixed(2)+' AED';if(c==='role')return <span className={'roleBadge role-'+v}>{ROLE_LABELS[v]||v}</span>;if(c==='is_active')return <span className={'statusBadge '+(v?'status-on':'status-off')}>{v?'فعّال':'موقوف'}</span>;return String(v)}
const PAGE_SIZE=10;
function Table({rows,cols,actions,searchable}){const[q,setQ]=useState('');const[page,setPage]=useState(0);const filtered=useMemo(()=>{if(!q)return rows;const s=q.trim().toLowerCase();return rows.filter(r=>cols.some(c=>String(r[c]??'').toLowerCase().includes(s)))},[rows,q,cols]);const pageCount=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));const pageRows=filtered.slice(page*PAGE_SIZE,page*PAGE_SIZE+PAGE_SIZE);useEffect(()=>{setPage(0)},[q,rows.length]);return <div>{searchable&&<input className="tableSearch" placeholder="بحث..." value={q} onChange={e=>setQ(e.target.value)}/>}<div className="table"><table><thead><tr>{cols.map(c=><th key={c}>{FIELD_LABELS[c]||c}</th>)}{actions&&<th></th>}</tr></thead><tbody>{pageRows.length===0&&<tr><td colSpan={cols.length+(actions?1:0)} className="empty">لا توجد بيانات</td></tr>}{pageRows.map(r=><tr key={r.id}>{cols.map(c=><td key={c}>{formatCell(c,r[c])}</td>)}{actions&&<td className="actionsCell">{actions(r)}</td>}</tr>)}</tbody></table></div>{pageCount>1&&<div className="pagination"><button type="button" disabled={page===0} onClick={()=>setPage(p=>p-1)}>السابق</button><span>{page+1} / {pageCount}</span><button type="button" disabled={page>=pageCount-1} onClick={()=>setPage(p=>p+1)}>التالي</button></div>}</div>}

createRoot(document.getElementById('root')).render(<App/>);
